name: Code Review
on:
  pull_request:
    paths-ignore:
      - 'lang/**'
      - '**.txt'
      - '**.md'
      - '.editorconfig'
      - 'CODEOWNERS'
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: the-events-calendar/action-tribe-phpcs@master
        with:
          github-bot-token: ${{ secrets.GH_BOT_TOKEN }}
